services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOMCAT_VERSION: ${TOMCAT_VERSION}
    ports:
      - "${HOST_PORT}:8080"
    #container_name: tomcat
    restart: always
    volumes:
      - ./logs:/usr/local/tomcat/logs
      - ./webapps:/usr/local/tomcat/webapps